{
  "hash": "88a79651ee1c42e0a8a763b1e607ae94",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Diagnóstico de calidad — ENOE 2024\"\nauthor: \"Angel Acis Delgadillo Ramos\"\ndate: today\n---\n\n## Objetivo\n\nAuditar la calidad del archivo de microdatos ENOE 2024 Trimestre 1 antes\nde cualquier análisis estadístico. Este diagnóstico certifica que el archivo\ncumple con los criterios de integridad, completitud y consistencia lógica\nesperados para una encuesta nacional del INEGI.\n\n**Fuente:** INEGI, Encuesta Nacional de Ocupación y Empleo 2024 T1  \n**URL:** https://www.inegi.org.mx/programas/enoe/15ymas/  \n**Fecha de descarga:** 12/05/2026  \n\n## Datos\n\nEl archivo `ENOE_SDEMT124.dbf` contiene el cuestionario sociodemográfico\nde la ENOE 2024 Trimestre 1. Cubre a la población de 15 años y más a nivel\nnacional con representatividad por entidad federativa.\n\n## Desarrollo\n\n### Lectura y limpieza inicial\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(foreign)\nlibrary(janitor)\nlibrary(skimr)\nlibrary(tidyverse)\nlibrary(here)\n\nenoe <- foreign::read.dbf(here::here(\"data/raw/ENOE_SDEMT124.dbf\"))\nenoe <- janitor::clean_names(enoe)\n\ncat(\"Filas:\", nrow(enoe), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFilas: 423866 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Columnas:\", ncol(enoe), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nColumnas: 114 \n```\n\n\n:::\n:::\n\n\n### Dimensiones y estructura\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(nrow(enoe) >= 300000 & nrow(enoe) <= 500000)\ncat(\"QA Dimensiones: PASADO\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQA Dimensiones: PASADO\n```\n\n\n:::\n:::\n\n\n### Completitud\n\nVariables con valores faltantes en el archivo:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenoe |>\n  skim() |>\n  dplyr::filter(n_missing > 0)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |       |\n|:------------------------|:------|\n|Name                     |enoe   |\n|Number of rows           |423866 |\n|Number of columns        |114    |\n|_______________________  |       |\n|Column type frequency:   |       |\n|factor                   |31     |\n|________________________ |       |\n|Group variables          |None   |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                                       |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------------------------------------|\n|loc           |    423866|          0.00|FALSE   |        0|:                                                |\n|mun           |      2851|          0.99|FALSE   |      213|002: 21576, 001: 20309, 005: 19274, 004: 18955   |\n|est_d_men     |     19595|          0.95|FALSE   |      430|008: 3139, 000: 2886, 001: 2846, 004: 2740       |\n|t_loc_men     |     19595|          0.95|FALSE   |        4|1: 230625, 4: 68117, 3: 52858, 2: 52671          |\n|par_c         |      7651|          0.98|FALSE   |       37|301: 152042, 101: 125370, 201: 69082, 408: 31212 |\n|sex           |      7651|          0.98|FALSE   |        2|2: 217508, 1: 198707                             |\n|eda           |      7651|          0.98|FALSE   |      100|23: 7391, 15: 7312, 18: 7119, 13: 7086           |\n|nac_dia       |      7651|          0.98|FALSE   |       32|99: 35324, 15: 13923, 10: 13855, 20: 13334       |\n|nac_mes       |      7651|          0.98|FALSE   |       13|08: 34871, 09: 34507, 10: 34081, 12: 32953       |\n|nac_anio      |      7651|          0.98|FALSE   |      112|200: 7376, 200: 7340, 200: 7198, 201: 7026       |\n|l_nac_c       |      7651|          0.98|FALSE   |       96|030: 22540, 007: 20738, 009: 18137, 011: 16603   |\n|cs_p12        |     30641|          0.93|FALSE   |        3|1: 370130, 2: 23034, 9: 61                       |\n|cs_p13_1      |     30641|          0.93|FALSE   |       11|02: 101442, 03: 98259, 04: 75047, 07: 70954      |\n|cs_p13_2      |     30641|          0.93|FALSE   |       10|3: 169995, 2: 52415, 6: 48179, 5: 36959          |\n|cs_p14_c      |    333685|          0.21|FALSE   |      171|041: 7757, 033: 6563, 042: 6121, 092: 4187       |\n|cs_p15        |    340034|          0.20|FALSE   |        4|3: 72939, 2: 9958, 1: 899, 9: 36                 |\n|cs_p16        |    333685|          0.21|FALSE   |        3|1: 69704, 2: 20284, 9: 193                       |\n|cs_p17        |     30641|          0.93|FALSE   |        3|2: 286443, 1: 106776, 9: 6                       |\n|n_hij         |    239715|          0.43|FALSE   |       27|00: 59803, 02: 37689, 03: 31283, 01: 23394       |\n|e_con         |     75885|          0.82|FALSE   |        7|6: 129654, 5: 120268, 1: 55946, 4: 19378         |\n|cs_p20a_1     |     11163|          0.97|FALSE   |        4|1: 410203, 2: 2103, 4: 245, 3: 152               |\n|cs_p20a_c     |     11163|          0.97|FALSE   |       64|007: 19261, 030: 17713, 015: 16889, 005: 16326   |\n|cs_p20b_1     |     11560|          0.97|FALSE   |        2|1: 408725, 2: 3581                               |\n|cs_p20b_c     |     11163|          0.97|FALSE   |      266|002: 20924, 001: 19695, 005: 18756, 004: 18518   |\n|cs_p20c_1     |    419888|          0.01|FALSE   |       11|03: 1826, 01: 727, 11: 478, 02: 339              |\n|cs_ad_mot     |    416215|          0.02|FALSE   |       11|06: 1977, 10: 1387, 01: 1298, 03: 858            |\n|cs_p21_des    |    422479|          0.00|FALSE   |      414|CAM: 264, SE : 243, IND: 50, CAM: 33             |\n|cs_ad_des     |    417441|          0.02|FALSE   |        4|1: 4900, 2: 1125, 3: 329, 9: 71                  |\n|cs_nr_mot     |    418538|          0.01|FALSE   |       11|06: 2056, 09: 1435, 08: 522, 03: 438             |\n|cs_p23_des    |    423611|          0.00|FALSE   |      176|CAM: 14, NO : 5, PRO: 5, DIC: 4                  |\n|cs_nr_ori     |    420495|          0.01|FALSE   |        4|1: 2720, 2: 515, 3: 132, 9: 4                    |\n\n\n:::\n:::\n\n\n### Variables clave — rangos y NAs\n\nLas variables de interés para el análisis del mercado laboral son:\n\n- `clase1` — condición de actividad\n- `dur_est` — duración de estudios\n- `ingocup` — ingreso mensual de ocupados\n- `eda` — edad\n- `sex` — sexo\n- `ent` — entidad federativa\n- `rama` — sector de actividad económica\n- `anios_esc` — años de escolaridad\n- `hrsocup` — horas trabajadas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvariables_clave <- c(\"clase1\", \"dur_est\", \"ingocup\", \"eda\", \"sex\",\n                     \"ent\", \"rama\", \"anios_esc\", \"hrsocup\")\n\nenoe |>\n  dplyr::select(any_of(variables_clave)) |>\n  skimr::skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                             |\n|:------------------------|:----------------------------|\n|Name                     |dplyr::select(enoe, any_o... |\n|Number of rows           |423866                       |\n|Number of columns        |9                            |\n|_______________________  |                             |\n|Column type frequency:   |                             |\n|factor                   |3                            |\n|numeric                  |6                            |\n|________________________ |                             |\n|Group variables          |None                         |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                                 |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------------------------------|\n|eda           |      7651|          0.98|FALSE   |      100|23: 7391, 15: 7312, 18: 7119, 13: 7086     |\n|sex           |      7651|          0.98|FALSE   |        2|2: 217508, 1: 198707                       |\n|ent           |         0|          1.00|FALSE   |       32|07: 20004, 30: 18050, 15: 17143, 05: 16769 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|      sd| p0| p25| p50|  p75|   p100|hist  |\n|:-------------|---------:|-------------:|-------:|-------:|--:|---:|---:|----:|------:|:-----|\n|clase1        |         0|             1|    1.17|    0.71|  0|   1|   1|    2|      2|▃▁▇▁▆ |\n|dur_est       |         0|             1|    1.78|    2.05|  0|   0|   0|    4|      6|▇▁▁▃▂ |\n|ingocup       |         0|             1| 3068.30| 6544.45|  0|   0|   0| 4800| 215000|▇▁▁▁▁ |\n|rama          |         0|             1|    1.57|    1.91|  0|   0|   0|    4|      7|▇▁▅▁▁ |\n|anios_esc     |         0|             1|    8.35|    6.46|  0|   4|   9|   12|     99|▇▁▁▁▁ |\n|hrsocup       |         0|             1|   18.63|   23.67|  0|   0|   0|   40|    168|▇▃▁▁▁ |\n\n\n:::\n:::\n\n\nLa variable `eda` se importa como factor. Se convierte a numérico para\npermitir operaciones aritméticas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenoe <- enoe |>\n  dplyr::mutate(eda = as.numeric(as.character(eda)))\n\nclass(enoe$eda)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\"\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(enoe$eda, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0 99\n```\n\n\n:::\n:::\n\n\n> **Regla general para microdatos INEGI:** el valor `99` en variables\n> demográficas siempre es código de no respuesta, nunca un valor real.\n\n### Consistencia lógica\n\nUna persona clasificada como ocupada (`clase1 == 1`) de 15 años o más\ndebería tener horas trabajadas registradas. Se cuantifican las excepciones:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninconsistencias <- enoe |>\n  dplyr::filter(eda >= 15 & clase1 == 1 & hrsocup == 0)\n\nn_inconsistencias <- nrow(inconsistencias)\npct_inconsistencias <- n_inconsistencias / nrow(enoe) * 100\n\ncat(\"Inconsistencias lógicas encontradas:\", n_inconsistencias, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nInconsistencias lógicas encontradas: 12965 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Porcentaje del total:\", round(pct_inconsistencias, 3), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPorcentaje del total: 3.059 %\n```\n\n\n:::\n:::\n\n\nLos 12,965 registros con ocupación declarada y cero horas trabajadas\n(3.059% del total) corresponden a ausencias temporales válidas: vacaciones,\nincapacidad médica o huelga. La tasa está dentro del rango esperado (< 5%)\ny no se consideran errores de captura.\n\n### Distribución de variables categóricas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nenoe |> dplyr::count(sex) |> dplyr::mutate(pct = n / sum(n) * 100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sex      n       pct\n1    1 198707 46.879674\n2    2 217508 51.315274\n3 <NA>   7651  1.805052\n```\n\n\n:::\n\n```{.r .cell-code}\nenoe |> dplyr::count(ent) |> dplyr::arrange(desc(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ent     n\n1   07 20004\n2   30 18050\n3   15 17143\n4   05 16769\n5   11 16436\n6   04 15878\n7   02 15815\n8   28 15632\n9   08 15490\n10  21 14886\n11  20 14027\n12  14 13691\n13  10 13562\n14  19 13438\n15  01 12581\n16  24 12520\n17  29 12494\n18  12 12346\n19  18 12253\n20  16 12085\n21  27 11860\n22  25 11819\n23  32 11666\n24  31 11610\n25  22 11540\n26  26 11076\n27  17 10554\n28  13 10511\n29  23 10318\n30  06 10069\n31  09  9389\n32  03  8354\n```\n\n\n:::\n\n```{.r .cell-code}\nenoe |> dplyr::count(rama) |> dplyr::arrange(desc(n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  rama      n\n1    0 229605\n2    4  90204\n3    3  37822\n4    2  31905\n5    1  15626\n6    6  15584\n7    5   1862\n8    7   1258\n```\n\n\n:::\n:::\n\n\n## QA y validación\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstopifnot(nrow(enoe) >= 300000 & nrow(enoe) <= 500000)\ncat(\"QA filas: PASADO\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQA filas: PASADO\n```\n\n\n:::\n\n```{.r .cell-code}\ncodigos_validos <- sprintf(\"%02d\", 1:32)\nstopifnot(all(enoe$ent %in% codigos_validos, na.rm = TRUE))\ncat(\"QA entidades: PASADO\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQA entidades: PASADO\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(sum(is.na(enoe$clase1)) == 0)\ncat(\"QA clase1 sin NAs: PASADO\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQA clase1 sin NAs: PASADO\n```\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(enoe$anios_esc[enoe$anios_esc != 99] <= 25, na.rm = TRUE))\ncat(\"QA anios_esc: PASADO\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nQA anios_esc: PASADO\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nDiagnóstico completado. Archivo listo para análisis.\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDiagnóstico completado. Archivo listo para análisis.\n```\n\n\n:::\n:::\n\n\n## Conclusiones\n\n- El archivo contiene 423,866 registros y 114 variables, dentro del rango\n  esperado para una muestra nacional de la ENOE.\n- Las variables `cs_p14_c`, `cs_p15` y `cs_p16` tienen alto porcentaje de\n  NAs por diseño del cuestionario — solo aplican a personas con estudios\n  superiores.\n- La variable `eda` requiere conversión de factor a numérico antes de\n  cualquier análisis.\n- El valor `99` en `anios_esc` es código de no respuesta y debe filtrarse\n  antes de calcular estadísticas de escolaridad.\n- La tasa de inconsistencias lógicas (3.059%) es consistente con ausencias\n  temporales válidas.\n\n## Nota metodológica\n\nLos microdatos utilizados corresponden al archivo `ENOE_SDEMT124.dbf` del\nprimer trimestre de 2024, descargado directamente del sitio oficial del\nINEGI. El archivo no se incluye en el repositorio por su tamaño. Para\nreproducir este análisis descarga el archivo desde la URL indicada y\ncolócalo en `data/raw/`.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}